export const TWELVE_MONTHS_TERM = 'TWELVE_MONTHS_TERM'
export const FIVE_YEARS_TERM = 'FIVE_YEARS_TERM'
export const FIRST_FACTORY_NUMBER = 'FIRST_FACTORY_NUMBER'
export const SECOND_FACTORY_NUMBER = "SECOND_FACTORY_NUMBER";
